<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('32', '/uploads/allimg/150508/1-15050R12452558.png');
$maNum = 1;
$myaddons[$maNum] = array('33', '/uploads/allimg/150508/1-15050R1263TE.png');
$maNum = 2;
$myaddons[$maNum] = array('34', '/uploads/allimg/150508/1-15050R12A4232.png');
$maNum = 3;
$myaddons[$maNum] = array('35', '/uploads/allimg/150508/1-15050R12G12Q.png');
$maNum = 4;
$myaddons[$maNum] = array('36', '/uploads/allimg/150508/1-15050R12H3H0.png');
$maNum = 5;
