<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('65', '/uploads/allimg/150521/1-15052116361I63.png');
$maNum = 1;
$myaddons[$maNum] = array('66', '/uploads/allimg/150521/1-1505211639463G.png');
$maNum = 2;
$myaddons[$maNum] = array('67', '/uploads/allimg/150521/1-150521164005552.png');
$maNum = 3;
$myaddons[$maNum] = array('68', '/uploads/allimg/150521/1-150521164021X4.png');
$maNum = 4;
$myaddons[$maNum] = array('69', '/uploads/allimg/150521/1-1505211A50E43.png');
$maNum = 5;
$myaddons[$maNum] = array('70', '/uploads/allimg/150521/1-1505211A529510.png');
$maNum = 6;
$myaddons[$maNum] = array('71', '/uploads/allimg/150521/1-1505211A549228.png');
$maNum = 7;
