<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('139', '/uploads/allimg/150818/1-150QQ62Z2236.JPG');
$maNum = 1;
$myaddons[$maNum] = array('140', '/uploads/allimg/150818/1-150QQ63424X7.jpg');
$maNum = 2;
$myaddons[$maNum] = array('141', '/uploads/allimg/150818/1-150QQ6350a50.jpg');
$maNum = 3;
$myaddons[$maNum] = array('142', '/uploads/allimg/150818/1-150QQ6352O19.jpg');
$maNum = 4;
$myaddons[$maNum] = array('143', '/uploads/allimg/150818/1-150QQ636111E.jpg');
$maNum = 5;
$myaddons[$maNum] = array('144', '/uploads/allimg/150818/1-150QQ6363b00.jpg');
$maNum = 6;
$myaddons[$maNum] = array('145', '/uploads/allimg/150818/1-150QQ63J5259.jpg');
$maNum = 7;
