<?php
$z[0]=Array("typelink","",29,46);
$z[1]=Array("arcurl","",80,95);
$z[2]=Array("title","",97,111);
$z[3]=Array("description","",140,160);
$z[4]=Array("arcurl","",230,245);
$z[5]=Array("global","",247,275);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",275,290);
$z[7]=Array("typeurl","",353,369);
$z[8]=Array("typename","",387,404);
$z[9]=Array("click","",458,472);
$z[10]=Array("stime","",522,536);

?>