<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="3";
$z[1]=Array("img"," /dede/uploads/allimg/150202/1-150202164410.jpg ",93,250);
$z[1][4]['ddimg']="/dede/uploads/allimg/150202/1-150202164410.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="650";
$z[1][4]['height']="345";
$z[2]=Array("img"," /dede/uploads/allimg/150202/1-150202164412.jpg ",252,409);
$z[2][4]['ddimg']="/dede/uploads/allimg/150202/1-150202164412.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="650";
$z[2][4]['height']="345";
$z[3]=Array("img"," /dede/uploads/allimg/150202/1-150202164413.jpg ",411,568);
$z[3][4]['ddimg']="/dede/uploads/allimg/150202/1-150202164413.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="650";
$z[3][4]['height']="345";
$z[4]=Array("img"," /dede/uploads/allimg/150202/1-150202164414.jpg ",570,727);
$z[4][4]['ddimg']="/dede/uploads/allimg/150202/1-150202164414.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="650";
$z[4][4]['height']="345";
$z[5]=Array("img"," /dede/uploads/allimg/150202/1-150202164415.jpg ",729,886);
$z[5][4]['ddimg']="/dede/uploads/allimg/150202/1-150202164415.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="650";
$z[5][4]['height']="345";

?>