<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,170);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",186,201);
$z[2]=Array("title","",217,231);
$z[3]=Array("pubdate","",299,345);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("softrank","",383,428);
$z[4][4]['function']="GetRankStar(@me)";
$z[5]=Array("language","",466,483);
$z[6]=Array("click","",521,535);
$z[7]=Array("description","",581,601);

?>