{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51624.jpg' text='武夷山的美景真是不错' width='800' height='513'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51624.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51625.jpg' text='武夷山的美景真是不错' width='800' height='500'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51625.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51626.jpg' text='武夷山的美景真是不错' width='800' height='513'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51626.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51627.jpg' text='武夷山的美景真是不错' width='798' height='499'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51627.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51628.jpg' text='武夷山的美景真是不错' width='800' height='501'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51628.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51629.jpg' text='武夷山的美景真是不错' width='800' height='511'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G51629.jpg {/dede:img}
