{dede:link text='V55-GBK版安装程序'} http://www.dedecms.com/upimg/soft/2009/DedecmsV55-GBK-Final.tar.gz {/dede:link}
{dede:link text='V55-UTF8版安装程序'} http://www.dedecms.com/upimg/soft/2009/DedecmsV55-UTF8-Final.tar.gz {/dede:link}
{dede:link text='V5.3.1到V5.5GBK升级程序'} http://updatenew.dedecms.com/downloads/v53gbk-upv55.zip {/dede:link}
{dede:link text='V5.3.1到V5.5UTF8升级程序'} http://updatenew.dedecms.com/downloads/v53utf8-upv55.zip {/dede:link}
{dede:link text='DedeCMS V5.5GBK + HDwiki V4.05 互动百科整合安装包'} http://www.dedecms.com/hdwiki/downloads/Dedecms55&HDwiki4.05_GBK-Final_0916.tar.gz {/dede:link}
{dede:link text='DedeCMS V5.5UTF8 + HDwiki V4.05 互动百科整合安装包'} http://www.dedecms.com/hdwiki/downloads/Dedecms55&HDwiki4.05_UTF8-Final_0916.tar.gz {/dede:link}
