<?php
$z[0]=Array("field","",23,46);
$z[0][4]['name']="id";
$z[1]=Array("arclist","\r\n                                    <a href=\"[field:arcurl/]\" target=\"_blank\">[field:image/]</a>\r\n                                    ",123,367);
$z[1][4]['row']="1";
$z[1][4]['orderby']="pubdate";
$z[1][4]['type']="image.";
$z[1][4]['imgwidth']="128";
$z[1][4]['imgheight']="300";
$z[1][4]['typeid']="20";
$z[2]=Array("arclist","\r\n								<li>\r\n									<span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n									<a href=\"[field:arcurl /]\">[field:title/]</a>\r\n								</li>\r\n								 ",406,622);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="5";

?>