[field:title/]<li><a href="#">1</a></li>
							{/dede}
                        	<li><a href="#">尾页</a></li>
                        </ul> -->
                        </div>
                        <div class="msg_form"><!--留言表单-->
                            <div class="title">我要留言</div>
                            <div class="content pure-u-1">
                                <form class="pure-form pure-form-aligned"  action="{dede:global.cfg_cmsurl