




<field:post itemname="应聘岗位" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:post>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:age itemname="年龄" autofield="1" type="select" isnull="true" default="16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65"  maxlength="250" page="">
</field:age>
