<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43432.jpg ",93,322);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43432.jpg";
$z[1][4]['text']="农家小院丝瓜架下";
$z[1][4]['width']="800";
$z[1][4]['height']="600";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43433.jpg ",324,553);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43433.jpg";
$z[2][4]['text']="农家小院丝瓜架下";
$z[2][4]['width']="800";
$z[2][4]['height']="600";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43434.jpg ",555,784);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43434.jpg";
$z[3][4]['text']="农家小院丝瓜架下";
$z[3][4]['width']="800";
$z[3][4]['height']="600";
$z[4]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43435.jpg ",786,1015);
$z[4][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43435.jpg";
$z[4][4]['text']="农家小院丝瓜架下";
$z[4][4]['width']="800";
$z[4][4]['height']="600";
$z[5]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43436.jpg ",1017,1246);
$z[5][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43436.jpg";
$z[5][4]['text']="农家小院丝瓜架下";
$z[5][4]['width']="800";
$z[5][4]['height']="600";

?>