{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43432.jpg' text='农家小院丝瓜架下' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43432.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43433.jpg' text='农家小院丝瓜架下' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43433.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43434.jpg' text='农家小院丝瓜架下' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43434.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43435.jpg' text='农家小院丝瓜架下' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43435.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43436.jpg' text='农家小院丝瓜架下' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G43436.jpg {/dede:img}
