<li class="msg_ul_li">
                                    <div class="msg_visitor">{dede:field name="name"/}</div>
                                    <div class="msg_content">{dede:field name="remark"/}</div>
                                    <div class="msg_date"><i>{dede:field name="date"/}</i></div>
                                    <ul class="msg_reply_ul">
                                        <li><em>XX部门：</em>来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复<i>1990-08-22</i></li>
                                        <li><em>XX部门：</em>来自部门的回复<i>1990-08-22</i></li>
                                        <li><em>XX部门：</em>来自部门的回复<i>1990-08-22</i></li>
                                    </ul>
                                    <div class="msg_support_oppose"><a href="#">赞</a>(10)&nbsp;&nbsp;&nbsp;<a href="#">反对</a>(9)</div>
                                </li>