{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40556.jpg' text='古镇建筑' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40556.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40557.jpg' text='好大的花啊' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40557.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40558.jpg' text='美丽的风景尽收眼底' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40558.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40559.jpg' text='美丽的风景尽收眼底' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40559.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40600.jpg' text='美丽的风景尽收眼底' width='800' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40600.jpg {/dede:img}
