<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40556.jpg ",93,310);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40556.jpg";
$z[1][4]['text']="古镇建筑";
$z[1][4]['width']="800";
$z[1][4]['height']="600";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40557.jpg ",312,532);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40557.jpg";
$z[2][4]['text']="好大的花啊";
$z[2][4]['width']="800";
$z[2][4]['height']="600";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40558.jpg ",534,766);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40558.jpg";
$z[3][4]['text']="美丽的风景尽收眼底";
$z[3][4]['width']="800";
$z[3][4]['height']="600";
$z[4]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40559.jpg ",768,1000);
$z[4][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40559.jpg";
$z[4][4]['text']="美丽的风景尽收眼底";
$z[4][4]['width']="800";
$z[4][4]['height']="600";
$z[5]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40600.jpg ",1002,1234);
$z[5][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G40600.jpg";
$z[5][4]['text']="美丽的风景尽收眼底";
$z[5][4]['width']="800";
$z[5][4]['height']="600";

?>