<?php
$z[0]=Array("field","",48,76);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",78,107);
$z[1][4]['name']="typename";
$z[2]=Array("field","",148,176);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n            <li><span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n          ",261,464);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>