<li class="msg_ul_li">
                                    <div class="msg_visitor">[field:name/]</div>
                                    <div class="msg_content">[field:remark/]</div>
                                    <div class="msg_date"><i>[field:date/]</i></div>
                                    <ul class="msg_reply_ul">
                                        <li><em>XX部门：</em>来自部门的回复来自部门的回复来自部门的回复来自部门的回复来自部门的回复<i>1990-08-22</i></li>
                                    </ul>
                                    <div class="msg_support_oppose"><a href="javascript:void(0);" onclick="support([field:id/])">赞</a>({dede:sql sql='select count(*) from cts_msg_support where msg_id=[field:name/]' appname='default'}[field:title/]{/dede})&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" onclick="oppose([field:id/])">反对</a>([field:oppose/])</div>
                                </li>