<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44302.jpg ",93,323);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44302.jpg";
$z[1][4]['text']="DedeCMS产品相关截图";
$z[1][4]['width']="800";
$z[1][4]['height']="506";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44303.jpg ",325,555);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44303.jpg";
$z[2][4]['text']="DedeCMS产品相关截图";
$z[2][4]['width']="800";
$z[2][4]['height']="519";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44304.jpg ",557,787);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44304.jpg";
$z[3][4]['text']="DedeCMS产品相关截图";
$z[3][4]['width']="800";
$z[3][4]['height']="463";

?>