{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44302.jpg' text='DedeCMS产品相关截图' width='800' height='506'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44302.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44303.jpg' text='DedeCMS产品相关截图' width='800' height='519'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44303.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44304.jpg' text='DedeCMS产品相关截图' width='800' height='463'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G44304.jpg {/dede:img}
