<table id='dedeinfolink'>
<tr>
	<td colspan='3' class='iftitle'>
		信息附加条件：
	</td>
</tr>
<tr>
	<td width='50'>&nbsp;地 区：</td>
	<td align='center' nowrap='yes'>
		<div>[field:linkallplace/]</div>
	</td>
	<td>
  	[field:nativeplace /]&nbsp;
	</td>
</tr>
<tr><td colspan='3' class='spline'>&nbsp;</td></tr>
<tr>
	<td>&nbsp;类 型：</td>
  <td align='center' nowrap='yes'>
  	<div>[field:linkalltype/]</div>
  </td>
  <td>
  	[field:infotype /]&nbsp;
  </td>
</tr>
<tr><td colspan='3' class='spline'>&nbsp;</td></tr>
</table>