<?php
$z[0]=Array("link"," http://pw.dedecms.com/dedecmsv51sp1.zip ",0,105);
$z[0][4]['text']="DedeCmsV5.1SP1 GBK独立安装包";
$z[1]=Array("link"," http://pw.dedecms.com/dedecmsv51sp1utf8.zip ",107,217);
$z[1][4]['text']="DedeCmsV5.1SP1 UTF8独立安装包";
$z[2]=Array("link"," http://www.dedecms.com/count.php?d=dedecmsv51sp1-PHPWindv632.zip ",219,364);
$z[2][4]['text']="DedeCmsV5.1SP1 GBK & PHPWind6.3.2整合安装包";

?>