<div style="text-align: center;">
	<span style="font-size:16px;"><strong><span style="font-family: Consolas, 'Lucida Console', monospace; white-space: pre-wrap;">电话：0877-6997872 </span><br />
	<span style="font-family: Consolas, 'Lucida Console', monospace; white-space: pre-wrap;">网址：www.cts-yn.com</span><br />
	<span style="font-family: Consolas, 'Lucida Console', monospace; white-space: pre-wrap;">传真：0877-6997908</span><br />
	<span style="font-family: Consolas, 'Lucida Console', monospace; white-space: pre-wrap;">地址：中国云南省玉溪市大营街常里蔡官屯89号</span></strong></span></div>
