<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",170,187);
$z[2]=Array("arcurl","",202,217);
$z[3]=Array("title","",233,247);
$z[4]=Array("pubdate","",296,342);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",367,381);
$z[6]=Array("scores","",406,421);
$z[7]=Array("description","",454,474);

?>