<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/dedecmsv3.1.rar ",0,119);
$z[0][4]['text']="DedeCms3.1全新安装程序";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/3.1litup3.1.rar ",121,239);
$z[1][4]['text']="DedeCms3.1Lit->3.1升级包";
$z[2]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/3.01up3.1.rar ",241,355);
$z[2][4]['text']="DedeCms3.01->3.1升级包";

?>