-->
                            <!--<div id="con_home_news_{dede:field name='id'/}" style="display: none;">-->
                                <!--<h5>-->
                                    <!--{dede:arclist row=1 orderby=pubdate type='image.' imgwidth='128' imgheight='300'}-->
                                    <!--<a href="[field:arcurl/]" target="_blank">[field:image/]</a>-->
                                    <!--{/dede:arclist}-->
                                <!--</h5>-->
                                <!--<ol>-->
                                    <!--{dede:arclist titlelen='60' row='5'}-->
                                    <!--<li>-->
                                        <!--<span>[field:pubdate function="MyDate('m-d',@me)"/]</span>-->
                                        <!--<a href="[field:arcurl /]">[field:title/]</a>-->
                                    <!--</li>-->
                                    <!--{/dede:arclist}-->
                                <!--</ol>-->
                            <!--</div>-->
                            <!--