{dede:link text='V53-GBK版安装程序本地下载'} http://www.dedecms.com/upimg/soft/2008/DedecmsV53-GBK-Final.tar.gz {/dede:link}
{dede:link text='V53-UTF8版安装程序本地下载'} http://www.dedecms.com/upimg/soft/2008/DedecmsV53-UTF8-Final.tar.gz {/dede:link}
{dede:link text='V53-繁體中文UTF-8版安裝程式本地下载'} http://www.dedecms.com/upimg/soft/2008/DedeCmsV53UTF8-BIG5.tar.gz {/dede:link}
{dede:link text='V3.1、4.1升级程序'} http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v3-v4-upToV5.3GBK.zip {/dede:link}
{dede:link text='V5.0、5.1 GBK版升级程序'} http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v5.1-gbk-up5.3.1.zip {/dede:link}
{dede:link text='V5.0、5.1 UTF8版升级程序'} http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v5.1-utf8-up5.3.1.zip {/dede:link}
{dede:link text='DedeCmsV5.3GBK + HDwiki 4.04 互动百科整合安装包'} http://www.dedecms.com/upimg/soft/2008/DedecmsV53&HDwiki-GBK-Final.tar.gz {/dede:link}
{dede:link text='DedeCmsV5.3UTF8 + HDwiki 4.04 互动百科整合安装包'} http://www.dedecms.com/upimg/soft/2008/DedecmsV53&HDwiki-UTF8-Final.tar.gz {/dede:link}
