<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/2008/DedecmsV53-GBK-Final.tar.gz ",0,133);
$z[0][4]['text']="V53-GBK版安装程序本地下载";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/2008/DedecmsV53-UTF8-Final.tar.gz ",135,270);
$z[1][4]['text']="V53-UTF8版安装程序本地下载";
$z[2]=Array("link"," http://www.dedecms.com/upimg/soft/2008/DedeCmsV53UTF8-BIG5.tar.gz ",272,418);
$z[2][4]['text']="V53-繁體中文UTF-8版安裝程式本地下载";
$z[3]=Array("link"," http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v3-v4-upToV5.3GBK.zip ",420,543);
$z[3][4]['text']="V3.1、4.1升级程序";
$z[4]=Array("link"," http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v5.1-gbk-up5.3.1.zip ",545,674);
$z[4][4]['text']="V5.0、5.1 GBK版升级程序";
$z[5]=Array("link"," http://updatenew.dedecms.com/DedeCmsUPV5.3Pack/v5.1-utf8-up5.3.1.zip ",676,807);
$z[5][4]['text']="V5.0、5.1 UTF8版升级程序";
$z[6]=Array("link"," http://www.dedecms.com/upimg/soft/2008/DedecmsV53&HDwiki-GBK-Final.tar.gz ",809,971);
$z[6][4]['text']="DedeCmsV5.3GBK + HDwiki 4.04 互动百科整合安装包";
$z[7]=Array("link"," http://www.dedecms.com/upimg/soft/2008/DedecmsV53&HDwiki-UTF8-Final.tar.gz ",973,1137);
$z[7][4]['text']="DedeCmsV5.3UTF8 + HDwiki 4.04 互动百科整合安装包";

?>