<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/dedecms4.0Rc1.rar ",0,112);
$z[0][4]['text']="DedeCms OX V4.0 Rc1";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/3.1upv40.rar ",114,231);
$z[1][4]['text']="DedeCms 3.1到4.0升级程序";
$z[2]=Array("link"," http://www.dedecms.com/upimg/soft/dedesoft/v4Patch1.rar ",233,392);
$z[2][4]['text']="DedeCms V4 Patch1(适用于4.月20日前下载的本程序的更新包)";

?>