{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50111.jpg' text='海岛风光' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50111.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50112.jpg' text='海岛风光' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50112.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50113.jpg' text='海岛风光' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50113.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50114.jpg' text='海岛风光' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50114.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50115.jpg' text='海岛风光' width='670' height='448'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50115.jpg {/dede:img}
