{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42130.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42130.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42131.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42131.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42132.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42132.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42133.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42133.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42134.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42134.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42135.jpg' text='流连忘返的香樟大道' width='640' height='480'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G42135.jpg {/dede:img}
