<?php
$z[0]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n\r\n",53,503);
$z[0][4]['item']="7";
$z[0][4]['name']="辅助插件";
$z[0][4]['display']="block";

?>