{dede:link text='DedeCms V5.1 GBK 全新安装包'} http://www.dedecms.com/upimg/soft/2008/dedecmsv51-gbk.zip {/dede:link}
{dede:link text='DedeCms V5.1 UTF-8 全新安装包'} http://www.dedecms.com/upimg/soft/2008/dedecmsv51-utf8.zip {/dede:link}
{dede:link text='DedeCms V5.1SP1 GBK 全新安装包'} http://pw.dedecms.com/dedecmsv51sp1.zip {/dede:link}
{dede:link text='DedeCms V5.1SP1 UTF-8 全新安装包'} http://pw.dedecms.com/dedecmsv51sp1utf8.zip {/dede:link}
{dede:link text='DedeCms V4.0 to 5.1GBK升级程序'} http://www.dedecms.com/upimg/soft/2008/dedecmsv51-v4up.zip {/dede:link}
{dede:link text='DedeCms V5.01 GBK to 5.1 GBK升级程序'} http://www.dedecms.com/upimg/soft/2008/dedecmsv51-501up.zip {/dede:link}
{dede:link text='DedeCms V5.01 UTF-8 to 5.1 UTF-8升级程序'} http://www.dedecms.com/upimg/soft/2008/dedecmsv51-501up-utf8.zip {/dede:link}
