<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53038.jpg ",93,310);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53038.jpg";
$z[1][4]['text']="花的照片";
$z[1][4]['width']="670";
$z[1][4]['height']="502";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53039.jpg ",312,529);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53039.jpg";
$z[2][4]['text']="花的照片";
$z[2][4]['width']="449";
$z[2][4]['height']="600";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53040.jpg ",531,748);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53040.jpg";
$z[3][4]['text']="花的照片";
$z[3][4]['width']="670";
$z[3][4]['height']="502";
$z[4]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041.jpg ",750,967);
$z[4][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041.jpg";
$z[4][4]['text']="花的照片";
$z[4][4]['width']="670";
$z[4][4]['height']="502";
$z[5]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041-50.jpg ",969,1192);
$z[5][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041-50.jpg";
$z[5][4]['text']="花的照片";
$z[5][4]['width']="670";
$z[5][4]['height']="502";

?>