{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53038.jpg' text='花的照片' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53038.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53039.jpg' text='花的照片' width='449' height='600'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53039.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53040.jpg' text='花的照片' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53040.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041.jpg' text='花的照片' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041-50.jpg' text='花的照片' width='670' height='502'} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G53041-50.jpg {/dede:img}
