<?php
$z[0]=Array("typelink","",21,38);
$z[1]=Array("arcurl","",64,79);
$z[2]=Array("title","",81,95);
$z[3]=Array("description","",116,136);
$z[4]=Array("arcurl","",190,205);
$z[5]=Array("global","",207,235);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",235,250);
$z[7]=Array("typeurl","",305,321);
$z[8]=Array("typename","",339,356);
$z[9]=Array("click","",402,416);
$z[10]=Array("stime","",458,472);

?>