<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",18,95);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",122,138);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",140,225);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",256,271);
$z[4]=Array("imgwidth","",285,303);
$z[5]=Array("alttext","",309,326);
$z[6]=Array("linkurl","",390,406);
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",408,494);
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",514,529);
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",569,649);
$z[9][4]['runphp']="yes";

?>