<?php
$z[0]=Array("typelink","",26,43);
$z[1]=Array("arcurl","",74,89);
$z[2]=Array("title","",91,105);
$z[3]=Array("description","",134,154);
$z[4]=Array("arcurl","",224,239);
$z[5]=Array("global","",241,269);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("arcurl","",269,284);
$z[7]=Array("typeurl","",347,363);
$z[8]=Array("typename","",381,398);
$z[9]=Array("click","",452,466);
$z[10]=Array("stime","",516,530);

?>