<field:filetype islist="1" itemname="文件类型" type="text" isnull="true" default="" rename="" />	
<field:language islist="1" itemname="语言" type="text" isnull="true" default="" rename="" />	
<field:softtype islist="1" itemname="软件类型" type="text" isnull="true" default="" rename="" />	
<field:accredit islist="1" itemname="授权方式" type="text" isnull="true" default="" rename="" />	
<field:os islist="1" itemname="操作系统" type="text" isnull="true" default="" rename="" />	
<field:softrank  islist="1" itemname="软件等级" type="int" isnull="true" default="3" rename="" function="GetRankStar(@me)" notsend="1"/>	
<field:officialUrl  itemname="官方网址" type="text" isnull="true" default="" rename="" />	
<field:officialDemo itemname="演示网址" type="text" isnull="true" default="" rename="" />	
<field:softsize  itemname="软件大小" type="text" isnull="true" default="" rename="" />	
<field:softlinks  itemname="软件地址" type="softlinks" isnull="true" default="" rename="" />	
<field:introduce  itemname="详细介绍" type="htmltext" isnull="trnue" default="" rename="" />	
<field:daccess islist="1" itemname="下载级别" type="int" isnull="true" default="0" rename="" function="" notsend="1"/>	
<field:needmoney islist="1" itemname="需要金币" type="int" isnull="true" default="0" rename="" function="" notsend="1" />