<?php
$z[0]=Array("field","",57,85);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",87,127);
$z[1][4]['name']="typename";
$z[2]=Array("field","",178,206);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",265,286);
$z[3][4]['name']="content";
$z[4]=Array("arclist","\r\n									<li><span class=\"date\">[field:pubdate\r\n											function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title\r\n											/]</a></li> ",331,544);
$z[4][4]['titlelen']="60";
$z[4][4]['row']="8";

?>