<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("include","",380,417);
$z[1][4]['filename']="cn_top.htm";
$z[2]=Array("field","",689,718);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                    <li><a id=\"submenuId<%=index%>\" href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                    ",793,960);
$z[3][4]['type']="son";
$z[4]=Array("include","",1308,1352);
$z[4][4]['filename']="cn_connection.htm";
$z[5]=Array("field","",1597,1626);
$z[5][4]['name']="position";
$z[6]=Array("field","",1722,1741);
$z[6][4]['name']="title";
$z[7]=Array("field","",1819,1875);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1919,1939);
$z[8][4]['name']="source";
$z[9]=Array("field","",1984,2004);
$z[9][4]['name']="writer";
$z[10]=Array("field","",2087,2114);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",2138,2161);
$z[11][4]['name']="id";
$z[12]=Array("field","",2166,2190);
$z[12][4]['name']="mid";
$z[13]=Array("field","",2407,2425);
$z[13][4]['name']="body";
$z[14]=Array("prenext","",2545,2570);
$z[14][4]['get']="pre";
$z[15]=Array("prenext","",2605,2631);
$z[15][4]['get']="next";
$z[16]=Array("include","",2864,2902);
$z[16][4]['filename']="cn_foot.htm";

?>