<?php
$z[0]=Array("include","",95,133);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("include","",358,395);
$z[1][4]['filename']="en_top.htm";
$z[2]=Array("field","",662,691);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",726,867);
$z[3][4]['type']="son";
$z[4]=Array("include","",1090,1134);
$z[4][4]['filename']="en_connection.htm";
$z[5]=Array("field","",1395,1424);
$z[5][4]['name']="position";
$z[6]=Array("field","",1530,1549);
$z[6][4]['name']="title";
$z[7]=Array("field","",1605,1661);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1683,1703);
$z[8][4]['name']="source";
$z[9]=Array("field","",1726,1746);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1791,1818);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",1842,1865);
$z[11][4]['name']="id";
$z[12]=Array("field","",1870,1894);
$z[12][4]['name']="mid";
$z[13]=Array("field","",2051,2069);
$z[13][4]['name']="body";
$z[14]=Array("prenext","",2187,2212);
$z[14][4]['get']="pre";
$z[15]=Array("prenext","",2235,2261);
$z[15][4]['get']="next";
$z[16]=Array("include","",2502,2540);
$z[16][4]['filename']="en_foot.htm";

?>