<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="warp_subCont">
    <p>
        <img src='<?php echo $GLOBALS['cfg_templets_skin']; ?>/images/sub_c1.jpg' /></p>
    <p class="phone">
        <div>电话：0877-6997872  </div>
        <div>网址：www.cts-yn.com</div>
		<div>传真：0877-6997908</div>
		<div>地址：中国云南省玉溪市大营街常里蔡官屯89号</div>

    </p>
    <p>
        <a href='<?php echo $GLOBALS['cfg_cmspath']; ?>/a/renliziyuan/rencaizhaopin'>
            <img src='<?php echo $GLOBALS['cfg_templets_skin']; ?>/images/sub_c2.jpg' /></a></p>
</div>