<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><!--bottom-->

<div class="bottom">
    <div class="copy">
        <a href="" target="_self" class="wanhu">
            Copyright &copy; 2015 Inc.All rights reserved |中烟施伟策（云南）再造烟叶有限公司
        </a>
    </div>

    <div class="horizontal_logo"></div>
</div>

<script type="text/javascript">
    $("img").error(function () {
        this.src = '<?php echo $GLOBALS['cfg_templets_skin']; ?>/images/nopic.gif';

    });
</script>


<!--bottom End-->