<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("global","",160,192);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",367,390);
$z[2][4]['name']="id";
$z[3]=Array("include","",587,624);
$z[3][4]['filename']="cn_top.htm";
$z[4]=Array("field","",902,931);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",966,1108);
$z[5][4]['type']="son";
$z[6]=Array("include","",1257,1301);
$z[6][4]['filename']="cn_connection.htm";
$z[7]=Array("field","",1562,1591);
$z[7][4]['name']="position";
$z[8]=Array("include","",3436,3474);
$z[8][4]['filename']="cn_foot.htm";

?>