<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",170,190);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",348,385);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",663,692);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",721,862);
$z[4][4]['type']="son";
$z[5]=Array("include","",1086,1130);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1391,1420);
$z[6][4]['name']="position";
$z[7]=Array("field","",1495,1516);
$z[7][4]['name']="content";
$z[8]=Array("include","",1707,1745);
$z[8][4]['filename']="cn_foot.htm";

?>