<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",205,228);
$z[1][4]['name']="id";
$z[2]=Array("include","",433,470);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",745,774);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",809,951);
$z[4][4]['type']="son";
$z[5]=Array("include","",1182,1226);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1487,1516);
$z[6][4]['name']="position";
$z[7]=Array("field","",1591,1612);
$z[7][4]['name']="content";
$z[8]=Array("include","",1803,1841);
$z[8][4]['filename']="cn_foot.htm";

?>