<?php
$z[0]=Array("include","",182,220);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",276,296);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",468,505);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",780,809);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",838,979);
$z[4][4]['type']="son";
$z[5]=Array("include","",1203,1247);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1508,1537);
$z[6][4]['name']="position";
$z[7]=Array("field","",1612,1633);
$z[7][4]['name']="content";
$z[8]=Array("include","",1824,1862);
$z[8][4]['filename']="cn_foot.htm";

?>