<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",170,190);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",362,399);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",629,658);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",687,828);
$z[4][4]['type']="son";
$z[5]=Array("include","",1052,1096);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1357,1386);
$z[6][4]['name']="position";
$z[7]=Array("field","",1461,1482);
$z[7][4]['name']="content";
$z[8]=Array("include","",1673,1711);
$z[8][4]['filename']="cn_foot.htm";

?>