<?php
$z[0]=Array("include","",182,220);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",313,336);
$z[1][4]['name']="id";
$z[2]=Array("include","",541,578);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",901,930);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",965,1107);
$z[4][4]['type']="son";
$z[5]=Array("include","",1331,1375);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1636,1665);
$z[6][4]['name']="position";
$z[7]=Array("field","",1740,1761);
$z[7][4]['name']="content";
$z[8]=Array("include","",1952,1990);
$z[8][4]['filename']="cn_foot.htm";

?>