<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("include","",441,478);
$z[1][4]['filename']="cn_top.htm";
$z[2]=Array("field","",692,721);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",750,894);
$z[3][4]['type']="son";
$z[4]=Array("include","",1116,1160);
$z[4][4]['filename']="cn_connection.htm";
$z[5]=Array("field","",1421,1450);
$z[5][4]['name']="position";
$z[6]=Array("field","",1747,1768);
$z[6][4]['name']="content";
$z[7]=Array("include","",1957,1995);
$z[7][4]['filename']="cn_foot.htm";

?>