<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",305,328);
$z[1][4]['name']="id";
$z[2]=Array("include","",533,570);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",784,813);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",848,993);
$z[4][4]['type']="son";
$z[5]=Array("include","",1215,1259);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1520,1549);
$z[6][4]['name']="position";
$z[7]=Array("field","",1846,1867);
$z[7][4]['name']="content";
$z[8]=Array("include","",2056,2094);
$z[8][4]['filename']="cn_foot.htm";

?>