<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("global","",160,192);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",304,327);
$z[2][4]['name']="id";
$z[3]=Array("include","",526,563);
$z[3][4]['filename']="cn_top.htm";
$z[4]=Array("field","",841,870);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",905,1047);
$z[5][4]['type']="son";
$z[6]=Array("include","",1271,1315);
$z[6][4]['filename']="cn_connection.htm";
$z[7]=Array("field","",1576,1605);
$z[7][4]['name']="position";
$z[8]=Array("arclist","\r\n                            <li>\r\n                                <a href=\"[field:arcurl/]\" target=\"_self\">[field:image/]</a>\r\n                            </li>\r\n                            ",1779,2079);
$z[8][4]['row']="5";
$z[8][4]['orderby']="pubdate";
$z[8][4]['type']="image.";
$z[8][4]['imgwidth']="250";
$z[8][4]['imgheight']="150";
$z[8][4]['typeid']="12";
$z[9]=Array("include","",2341,2379);
$z[9][4]['filename']="cn_foot.htm";

?>