<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",205,228);
$z[1][4]['name']="id";
$z[2]=Array("include","",433,470);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",737,766);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",801,943);
$z[4][4]['type']="son";
$z[5]=Array("include","",1167,1211);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",1472,1501);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",1608,1992);
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",2041,2119);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="9";
$z[9]=Array("include","",2335,2373);
$z[9][4]['filename']="cn_foot.htm";

?>