<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("field","",168,188);
$z[1][4]['name']="typeid";
$z[2]=Array("global","",556,581);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("include","",1117,1154);
$z[3][4]['filename']="cn_top.htm";
$z[4]=Array("field","",1421,1450);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",1479,1619);
$z[5][4]['type']="son";
$z[6]=Array("include","",1843,1887);
$z[6][4]['filename']="cn_connection.htm";
$z[7]=Array("field","",2148,2177);
$z[7][4]['name']="position";
$z[8]=Array("global","",2436,2461);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("include","",3644,3682);
$z[9][4]['filename']="cn_foot.htm";

?>