<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("global","",537,562);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("include","",1098,1135);
$z[2][4]['filename']="cn_top.htm";
$z[3]=Array("field","",1402,1431);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href=''>[field:typename/]</a></li>\r\n      	",1460,1584);
$z[4][4]['type']="son";
$z[5]=Array("include","",1808,1852);
$z[5][4]['filename']="cn_connection.htm";
$z[6]=Array("field","",2113,2142);
$z[6][4]['name']="position";
$z[7]=Array("global","",2401,2426);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("include","",3609,3647);
$z[8][4]['filename']="cn_foot.htm";

?>