<?php
$z[0]=Array("include","",76,111);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",438,472);
$z[1][4]['filename']="top.htm";
$z[2]=Array("field","",686,715);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",744,888);
$z[3][4]['type']="son";
$z[4]=Array("include","",1110,1151);
$z[4][4]['filename']="connection.htm";
$z[5]=Array("field","",1412,1441);
$z[5][4]['name']="position";
$z[6]=Array("field","",1738,1759);
$z[6][4]['name']="content";
$z[7]=Array("include","",1948,1983);
$z[7][4]['filename']="foot.htm";

?>