{dede:link text='V5.01 GBK正式版全新安装包'} http://www.dedecms.com/upimg/soft/dedecmsv5f-gbk.zip {/dede:link}
{dede:link text='V5.01 UTF8版安装包'} http://www.dedecms.com/upimg/soft/dedecmsv5f-utf8.zip {/dede:link}
{dede:link text='V5 2007Rc1版升级安装包'} http://www.dedecms.com/upimg/soft/dedecmsv5f-rcup.zip {/dede:link}
{dede:link text='DedeCmsV4 版升级安装包'} http://www.dedecms.com/upimg/soft/dedecmsv5f-v4up.zip {/dede:link}
