<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/dedecmsv5f-gbk.zip ",0,118);
$z[0][4]['text']="V5.01 GBK正式版全新安装包";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/dedecmsv5f-utf8.zip ",120,228);
$z[1][4]['text']="V5.01 UTF8版安装包";
$z[2]=Array("link"," http://www.dedecms.com/upimg/soft/dedecmsv5f-rcup.zip ",230,344);
$z[2][4]['text']="V5 2007Rc1版升级安装包";
$z[3]=Array("link"," http://www.dedecms.com/upimg/soft/dedecmsv5f-v4up.zip ",346,460);
$z[3][4]['text']="DedeCmsV4 版升级安装包";

?>