<?php
$z[0]=Array("global","",194,226);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","",387,415);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",417,457);
$z[2][4]['name']="typename";
$z[3]=Array("field","",508,536);
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n									<li><span class=\"date\">[field:pubdate\r\n											function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title\r\n											/]</a></li> ",632,845);
$z[4][4]['titlelen']="60";
$z[4][4]['row']="8";

?>