<?php
$z[0]=Array("field","",23,46);
$z[0][4]['name']="id";
$z[1]=Array("arclist","<a href=\"[field:arcurl/]\" target=_blank>[field:image/]</a>",75,229);
$z[1][4]['row']="1";
$z[1][4]['orderby']="pubdate";
$z[1][4]['type']="image.";
$z[1][4]['imgwidth']="128";
$z[1][4]['imgheight']="300";
$z[2]=Array("arclist","<li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title/]</a>",238,396);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="5";

?>