<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("include","",381,418);
$z[1][4]['filename']="en_top.htm";
$z[2]=Array("field","",690,719);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                    <li><a id=\"submenuId<%=index%>\" href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                    ",776,943);
$z[3][4]['type']="son";
$z[4]=Array("include","",1291,1335);
$z[4][4]['filename']="en_connection.htm";
$z[5]=Array("field","",1580,1609);
$z[5][4]['name']="position";
$z[6]=Array("field","",1705,1724);
$z[6][4]['name']="title";
$z[7]=Array("field","",1802,1858);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1902,1922);
$z[8][4]['name']="source";
$z[9]=Array("field","",1968,1988);
$z[9][4]['name']="writer";
$z[10]=Array("field","",2072,2099);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",2123,2146);
$z[11][4]['name']="id";
$z[12]=Array("field","",2151,2175);
$z[12][4]['name']="mid";
$z[13]=Array("field","",2394,2412);
$z[13][4]['name']="body";
$z[14]=Array("prenext","",2532,2557);
$z[14][4]['get']="pre";
$z[15]=Array("prenext","",2592,2618);
$z[15][4]['get']="next";
$z[16]=Array("include","",2851,2889);
$z[16][4]['filename']="en_foot.htm";

?>