<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("include","",329,366);
$z[1][4]['filename']="en_top.htm";
$z[2]=Array("field","",644,673);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",702,843);
$z[3][4]['type']="son";
$z[4]=Array("include","",1067,1111);
$z[4][4]['filename']="en_connection.htm";
$z[5]=Array("field","",1372,1401);
$z[5][4]['name']="position";
$z[6]=Array("field","",1510,1529);
$z[6][4]['name']="title";
$z[7]=Array("field","",1615,1671);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1719,1739);
$z[8][4]['name']="source";
$z[9]=Array("field","",1788,1808);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1899,1926);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",1950,1973);
$z[11][4]['name']="id";
$z[12]=Array("field","",1978,2002);
$z[12][4]['name']="mid";
$z[13]=Array("field","",2243,2261);
$z[13][4]['name']="body";
$z[14]=Array("prenext","",2397,2422);
$z[14][4]['get']="pre";
$z[15]=Array("prenext","",2461,2487);
$z[15][4]['get']="next";
$z[16]=Array("include","",2754,2792);
$z[16][4]['filename']="en_foot.htm";

?>