<?php
$z[0]=Array("global","",345,377);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",476,508);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",544,576);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",627,659);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",744,776);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",894,919);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1296,1328);
$z[6][4]['name']="cfg_templets_skin";

?>