<?php
$z[0]=Array("include","",182,220);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",314,337);
$z[1][4]['name']="id";
$z[2]=Array("include","",542,579);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",854,883);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",912,1054);
$z[4][4]['type']="son";
$z[5]=Array("include","",1278,1322);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1583,1612);
$z[6][4]['name']="position";
$z[7]=Array("field","",1687,1708);
$z[7][4]['name']="content";
$z[8]=Array("include","",1899,1937);
$z[8][4]['filename']="en_foot.htm";

?>