<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",208,231);
$z[1][4]['name']="id";
$z[2]=Array("include","",436,473);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",747,776);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",805,947);
$z[4][4]['type']="son";
$z[5]=Array("include","",1171,1215);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1476,1505);
$z[6][4]['name']="position";
$z[7]=Array("field","",1580,1601);
$z[7][4]['name']="content";
$z[8]=Array("include","",1792,1830);
$z[8][4]['filename']="en_foot.htm";

?>