<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",271,294);
$z[1][4]['name']="id";
$z[2]=Array("include","",499,536);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",810,839);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",874,1016);
$z[4][4]['type']="son";
$z[5]=Array("include","",1068,1112);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1373,1402);
$z[6][4]['name']="position";
$z[7]=Array("field","",1477,1498);
$z[7][4]['name']="content";
$z[8]=Array("include","",1689,1727);
$z[8][4]['filename']="en_foot.htm";

?>