<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",206,229);
$z[1][4]['name']="id";
$z[2]=Array("include","",434,471);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",746,775);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",804,946);
$z[4][4]['type']="son";
$z[5]=Array("include","",1170,1214);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1475,1504);
$z[6][4]['name']="position";
$z[7]=Array("field","",1579,1600);
$z[7][4]['name']="content";
$z[8]=Array("include","",1791,1829);
$z[8][4]['filename']="en_foot.htm";

?>