<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",306,329);
$z[1][4]['name']="id";
$z[2]=Array("include","",534,571);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",785,814);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",843,988);
$z[4][4]['type']="son";
$z[5]=Array("include","",1210,1254);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1505,1534);
$z[6][4]['name']="position";
$z[7]=Array("field","",1829,1850);
$z[7][4]['name']="content";
$z[8]=Array("include","",2039,2077);
$z[8][4]['filename']="en_foot.htm";

?>