<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",168,188);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",360,397);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",672,701);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",730,871);
$z[4][4]['type']="son";
$z[5]=Array("include","",1095,1139);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1390,1419);
$z[6][4]['name']="position";
$z[7]=Array("field","",1493,1514);
$z[7][4]['name']="content";
$z[8]=Array("include","",1705,1743);
$z[8][4]['filename']="en_foot.htm";

?>