<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",369,392);
$z[1][4]['name']="id";
$z[2]=Array("include","",597,634);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",848,877);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n        <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",906,1051);
$z[4][4]['type']="son";
$z[5]=Array("include","",1273,1317);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1568,1597);
$z[6][4]['name']="position";
$z[7]=Array("field","",1892,1913);
$z[7][4]['name']="content";
$z[8]=Array("include","",2102,2140);
$z[8][4]['filename']="en_foot.htm";

?>