<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",170,190);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",362,399);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",677,706);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",735,876);
$z[4][4]['type']="son";
$z[5]=Array("include","",1100,1144);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1405,1434);
$z[6][4]['name']="position";
$z[7]=Array("field","",1509,1530);
$z[7][4]['name']="content";
$z[8]=Array("include","",1721,1759);
$z[8][4]['filename']="en_foot.htm";

?>