<?php
$z[0]=Array("include","",72,110);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("global","",129,161);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",1272,1309);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("global","",1341,1373);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1468,1500);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1773,1805);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("channel","<a\r\n                    href=\"javascript:void(0);\" id=\"home_news[field:id/]\" onmouseover=\"setTab('home_news',[field:id/])\">[field:typename/]</a>",1928,2123);
$z[6][4]['type']="son";
$z[6][4]['typeid']="3";
$z[7]=Array("channelartlist","\r\n                    <div id=\"con_home_news_{dede:field name='id'/}\" style=\"display: none;\"><h5>{dede:arclist row=1\r\n                        orderby=pubdate type='image.' imgwidth='128' imgheight='300'}<a href=\"[field:arcurl/]\"\r\n                                                                                        target=_blank>[field:image/]</a>{/dede:arclist}\r\n                    </h5>\r\n                        <ol>{dede:arclist titlelen='60' row='5'}\r\n                            <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title/]</a>{/dede:arclist}\r\n                        </ol>\r\n                    </div>\r\n                    ",2184,2931);
$z[7][4]['typeid']="3";
$z[8]=Array("global","",3114,3146);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",3433,3459);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("global","",3667,3699);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",3882,3908);
$z[11][4]['name']="cfg_cmspath";
$z[12]=Array("arclist","\r\n                    <li><a href=\"[]field:arcurl/]'\">[field:title/]</a>",5426,5562);
$z[12][4]['typeid']="26";
$z[12][4]['row']="5";
$z[12][4]['titlelen']="60";
$z[13]=Array("include","",6047,6085);
$z[13][4]['filename']="en_foot.htm";

?>