<?php
$z[0]=Array("include","",182,220);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",377,400);
$z[1][4]['name']="id";
$z[2]=Array("include","",605,642);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",917,946);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",975,1117);
$z[4][4]['type']="son";
$z[5]=Array("include","",1341,1385);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1646,1675);
$z[6][4]['name']="position";
$z[7]=Array("field","",1750,1771);
$z[7][4]['name']="content";
$z[8]=Array("include","",1962,2000);
$z[8][4]['filename']="en_foot.htm";

?>