<?php
$z[0]=Array("include","",76,114);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("global","",160,192);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",305,328);
$z[2][4]['name']="id";
$z[3]=Array("include","",531,568);
$z[3][4]['filename']="en_top.htm";
$z[4]=Array("field","",846,875);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",904,1046);
$z[5][4]['type']="son";
$z[6]=Array("include","",1270,1314);
$z[6][4]['filename']="en_connection.htm";
$z[7]=Array("field","",1575,1604);
$z[7][4]['name']="position";
$z[8]=Array("arclist","\r\n                            <li>\r\n                                <a href=\"[field:arcurl/]\" target=\"_self\">[field:image/]</a>\r\n                            </li>\r\n                            ",1778,2078);
$z[8][4]['row']="5";
$z[8][4]['orderby']="pubdate";
$z[8][4]['type']="image.";
$z[8][4]['imgwidth']="250";
$z[8][4]['imgheight']="150";
$z[8][4]['typeid']="42";
$z[9]=Array("include","",2340,2378);
$z[9][4]['filename']="en_foot.htm";

?>