<?php
$z[0]=Array("include","",77,115);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",209,232);
$z[1][4]['name']="id";
$z[2]=Array("include","",437,474);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",736,765);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",794,936);
$z[4][4]['type']="self";
$z[5]=Array("include","",1044,1088);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1349,1378);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",1485,1868);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1917,1995);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="9";
$z[9]=Array("include","",2211,2249);
$z[9][4]['filename']="en_foot.htm";

?>