<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",269,292);
$z[1][4]['name']="id";
$z[2]=Array("include","",497,534);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",801,830);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",859,1001);
$z[4][4]['type']="son";
$z[5]=Array("include","",1225,1269);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1530,1559);
$z[6][4]['name']="position";
$z[7]=Array("arclist","\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n                        ",1714,2162);
$z[7][4]['titlelen']="120";
$z[7][4]['pagesize']="10";
$z[7][4]['typeid']="26";
$z[7][4]['tagid']="story";
$z[8]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",2184,2568);
$z[8][4]['pagesize']="10";
$z[9]=Array("arcpagelist","",2642,2675);
$z[9][4]['tagid']="story";
$z[10]=Array("include","",2890,2928);
$z[10][4]['filename']="en_foot.htm";

?>