<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("field","",206,229);
$z[1][4]['name']="id";
$z[2]=Array("include","",434,471);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",735,764);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId[field:id/]\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",793,935);
$z[4][4]['type']="son";
$z[5]=Array("include","",1159,1203);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",1464,1493);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",1600,1983);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2032,2110);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="9";
$z[9]=Array("include","",2326,2364);
$z[9][4]['filename']="en_foot.htm";

?>