<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="en_head.htm";
$z[1]=Array("global","",538,563);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("include","",1099,1136);
$z[2][4]['filename']="en_top.htm";
$z[3]=Array("field","",1403,1432);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",1461,1603);
$z[4][4]['type']="self";
$z[5]=Array("include","",1827,1871);
$z[5][4]['filename']="en_connection.htm";
$z[6]=Array("field","",2132,2161);
$z[6][4]['name']="position";
$z[7]=Array("global","",2421,2446);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("include","",3630,3668);
$z[8][4]['filename']="en_foot.htm";

?>