<?php
$z[0]=Array("include","",182,217);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",273,293);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",465,499);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",774,803);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",832,973);
$z[4][4]['type']="son";
$z[5]=Array("include","",1197,1238);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1499,1528);
$z[6][4]['name']="position";
$z[7]=Array("field","",1603,1624);
$z[7][4]['name']="content";
$z[8]=Array("include","",1815,1850);
$z[8][4]['filename']="foot.htm";

?>