<?php
$z[0]=Array("global","",444,476);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",565,597);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",633,665);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",716,748);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",826,858);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("field","",965,985);
$z[5][4]['name']="typeid";
$z[6]=Array("include","",1157,1192);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1422,1451);
$z[7][4]['name']="typename";
$z[8]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",1480,1621);
$z[8][4]['type']="son";
$z[9]=Array("include","",1845,1886);
$z[9][4]['filename']="connection.htm";
$z[10]=Array("field","",2147,2176);
$z[10][4]['name']="position";
$z[11]=Array("channelartlist","\r\n						<dl class=\"tbox\">\r\n							<dt>\r\n								<strong><a href=\"{dede:field name='typeurl'/}\">{dede:field\r\n										name='typename'/}</a></strong><span class=\"more\"><a\r\n									href=\"{dede:field name='typeurl'/}\">更多...</a></span>\r\n							</dt>\r\n							<dd>\r\n\r\n								<ul class=\"articleList\">\r\n									{dede:arclist titlelen='60' row='8'}\r\n									<li><span class=\"date\">[field:pubdate\r\n											function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title\r\n											/]</a></li> {/dede:arclist}\r\n								</ul>\r\n							</dd>\r\n						</dl>\r\n						",2280,2896);
$z[12]=Array("include","",3102,3137);
$z[12][4]['filename']="foot.htm";

?>