<?php
$z[0]=Array("include","",76,111);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",167,187);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",359,393);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",671,700);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",729,870);
$z[4][4]['type']="son";
$z[5]=Array("include","",1094,1135);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1396,1425);
$z[6][4]['name']="position";
$z[7]=Array("field","",1500,1521);
$z[7][4]['name']="content";
$z[8]=Array("include","",1712,1747);
$z[8][4]['filename']="foot.htm";

?>