<?php
$z[0]=Array("include","",76,111);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",167,187);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",359,393);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",623,652);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",681,822);
$z[4][4]['type']="son";
$z[5]=Array("include","",1046,1087);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1348,1377);
$z[6][4]['name']="position";
$z[7]=Array("field","",1452,1473);
$z[7][4]['name']="content";
$z[8]=Array("include","",1664,1699);
$z[8][4]['filename']="foot.htm";

?>