<?php
$z[0]=Array("include","",72,107);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",1269,1303);
$z[2][4]['filename']="top.htm";
$z[3]=Array("global","",1335,1367);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1462,1494);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1767,1799);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("channel","<a\r\n                    href=\"javascript:void(0);\" id=\"home_news[field:id/]\" onmouseover=\"setTab('home_news',[field:id/])\">[field:typename/]</a>",1922,2117);
$z[6][4]['type']="son";
$z[6][4]['typeid']="3";
$z[7]=Array("channelartlist","\r\n                    <div id=\"con_home_news_{dede:field name='id'/}\" style=\"display: none;\"><h5>{dede:arclist row=1\r\n                        orderby=pubdate type='image.' imgwidth='128' imgheight='300'}<a href=\"[field:arcurl/]\"\r\n                                                                                        target=_blank>[field:image/]</a>{/dede:arclist}\r\n                    </h5>\r\n                        <ol>{dede:arclist titlelen='60' row='5'}\r\n                            <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title/]</a>{/dede:arclist}\r\n                        </ol>\r\n                    </div>\r\n                    ",2178,2925);
$z[7][4]['typeid']="3";
$z[8]=Array("global","",3116,3148);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",3435,3461);
$z[9][4]['name']="cfg_cmspath";
$z[10]=Array("global","",3671,3703);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",3886,3912);
$z[11][4]['name']="cfg_cmspath";
$z[12]=Array("arclist","\r\n                    <li><a href=\"[]field:arcurl/]'\">[field:title/]</a>",5430,5566);
$z[12][4]['typeid']="26";
$z[12][4]['row']="5";
$z[12][4]['titlelen']="60";
$z[13]=Array("include","",6051,6086);
$z[13][4]['filename']="foot.htm";

?>