<?php
$z[0]=Array("include","",76,111);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",265,285);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",457,491);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",705,734);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",761,901);
$z[4][4]['type']="son";
$z[5]=Array("include","",1125,1166);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1427,1456);
$z[6][4]['name']="position";
$z[7]=Array("field","",1780,1801);
$z[7][4]['name']="content";
$z[8]=Array("include","",1990,2025);
$z[8][4]['filename']="foot.htm";

?>