<?php
$z[0]=Array("include","",74,109);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",165,185);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",357,391);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",666,695);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",724,865);
$z[4][4]['type']="son";
$z[5]=Array("include","",1089,1130);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1391,1420);
$z[6][4]['name']="position";
$z[7]=Array("field","",1495,1516);
$z[7][4]['name']="content";
$z[8]=Array("include","",1707,1742);
$z[8][4]['filename']="foot.htm";

?>