<?php
$z[0]=Array("include","",74,109);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",165,185);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",357,391);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",658,687);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",716,857);
$z[4][4]['type']="son";
$z[5]=Array("include","",1081,1122);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1383,1412);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",1519,1902);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1951,2029);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="9";
$z[9]=Array("include","",2245,2280);
$z[9][4]['filename']="foot.htm";

?>