<?php
$z[0]=Array("include","",104,139);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",195,215);
$z[1][4]['name']="typeid";
$z[2]=Array("include","",387,421);
$z[2][4]['filename']="top.htm";
$z[3]=Array("field","",694,723);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",752,893);
$z[4][4]['type']="son";
$z[5]=Array("include","",1117,1158);
$z[5][4]['filename']="connection.htm";
$z[6]=Array("field","",1419,1448);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n\r\n   							<li>\r\n                            【[field:typelink/]】\r\n                            <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                            <span>[[field:pubdate function=\"GetDateTimeMK(@me)\"/]]</span>\r\n                            <span>点击：[field:click/] 次</span>\r\n                            </li>\r\n    ",1555,1938);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",1987,2065);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="9";
$z[9]=Array("include","",2281,2316);
$z[9][4]['filename']="foot.htm";

?>