<?php
$z[0]=Array("include","",76,111);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",336,370);
$z[1][4]['filename']="top.htm";
$z[2]=Array("field","",584,613);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",642,786);
$z[3][4]['type']="son";
$z[4]=Array("include","",1008,1049);
$z[4][4]['filename']="connection.htm";
$z[5]=Array("field","",1310,1339);
$z[5][4]['name']="position";
$z[6]=Array("include","",2185,2220);
$z[6][4]['filename']="foot.htm";

?>