<?php
$z[0]=Array("include","",74,109);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",165,185);
$z[1][4]['name']="typeid";
$z[2]=Array("global","",553,578);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("include","",1114,1148);
$z[3][4]['filename']="top.htm";
$z[4]=Array("field","",1415,1444);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n      <li><a id=\"submenuId<%=index%>\"  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",1473,1615);
$z[5][4]['type']="self";
$z[6]=Array("include","",1839,1880);
$z[6][4]['filename']="connection.htm";
$z[7]=Array("field","",2141,2170);
$z[7][4]['name']="position";
$z[8]=Array("global","",2429,2454);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("include","",3637,3672);
$z[9][4]['filename']="foot.htm";

?>