<?php
$z[0]=Array("item","",0,83);
$z[0][4]['ico']="images/addnews.gif";
$z[0][4]['link']="content_list.php";
$z[0][4]['title']="文档列表";
$z[1]=Array("item","",85,171);
$z[1][4]['ico']="images/menuarrow.gif";
$z[1][4]['link']="feedback_main.php";
$z[1][4]['title']="评论管理";
$z[2]=Array("item","",173,256);
$z[2][4]['ico']="images/manage1.gif";
$z[2][4]['link']="public_guide.php";
$z[2][4]['title']="内容发布";

?>