<?php
$z[0]=Array("include","",74,112);
$z[0][4]['filename']="cn_head.htm";
$z[1]=Array("include","",133,170);
$z[1][4]['filename']="cn_top.htm";
$z[2]=Array("global","",288,343);
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("list","\r\n\r\n                <li>\r\n                    [field:typelink/]\r\n                    <a href=\"[field:arcurl/]\">[field:title/]</a>\r\n                    <p>[field:description/]...</p>\r\n                    <span>\r\n                        <a href=\"[field:arcurl/]\">[field:global.cfg_basehost/][field:arcurl/]</a>\r\n                        <small>分类：</small><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a>\r\n                        <small>点击：</small>[field:click/]\r\n                        <small>日期：</small>[field:stime/]\r\n                    </span>\r\n                </li>\r\n                ",431,1087);
$z[3][4]['perpage']="20";
$z[4]=Array("pagelist","",1144,1222);
$z[4][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[4][4]['listsize']="9";
$z[5]=Array("include","",1269,1307);
$z[5][4]['filename']="cn_foot.htm";

?>